const Paths = {
  DEFAULT: '../../test/res/default.epub',
  UNZIPPED_DEFAULT: '../../test/res/default',
  ENCRYPTED_DEFAULT: '../../test/res/encryptedDefault.epub',
  EXPECTED_DEFAULT_CONTEXT: '../../test/res/expectedDefaultContext.json',
  EXPECTED_DEFAULT_BOOK: '../../test/res/expectedDefaultBook.json',
  DEFAULT_COVER: '../../test/res/cryptor/Cover.xhtml',
  INVALID_PACKAGE1: '../../test/res/invalidPackage1.epub',
  INVALID_PACKAGE2: '../../test/res/invalidPackage2.epub',
  INVALID_PACKAGE3: '../../test/res/invalidPackage3.epub',
  INVALID_PACKAGE4: '../../test/res/invalidPackage4.epub',
  NCX_FILE_MISSING: '../../test/res/ncxFileMissing.epub',
  NCX_ID_NOT_MATCHED: '../../test/res/ncxIdNotMatched.epub',
  NCX_MISSING_IN_OPF: '../../test/res/ncxMissingInOpf.epub',
  META_INF_MISSING: '../../test/res/metainfMissing.epub',
  OPF_MISSING: '../../test/res/opfMissing.epub',
  EXTRACT_STYLE: '../../test/res/extractStyle.epub',
  UNZIPPED_EXTRACT_STYLE: '../../test/res/extractStyle',
  EXPECTED_EXTRACT_STYLE_BOOK: '../../test/res/expectedExtractStyleBook.json',
  SPINE_LOADER_ORIGIN: '../../test/res/spineLoader/origin.xhtml',
  SPINE_LOADER_NO_OPTIONS: '../../test/res/spineLoader/noOptions.xhtml',
  SPINE_LOADER_BASE_PATH: '../../test/res/spineLoader/basePath.xhtml',
  SPINE_LOADER_NO_ADAPTER: '../../test/res/spineLoader/noAdapter.json',
  SPINE_LOADER_ADAPTER: '../../test/res/spineLoader/adapter.json',
  SPINE_LOADER_CSS_OPTIONS: '../../test/res/spineLoader/cssOptions.xhtml',
  SPINE_LOADER_CSS_OPTIONS_AND_BASE_PATH: '../../test/res/spineLoader/cssOptionsAndBasePath.xhtml',
  SPINE_LOADER_SERIALIZED_ANCHOR: '../../test/res/spineLoader/serializedAnchor.xhtml',
  SPINE_LOADER_IGNORE_SCRIPT: '../../test/res/spineLoader/ignoreScript.xhtml',
  EDGE_CASES1: '../../test/res/edgeCases1.epub',
  EDGE_CASES2: '../../test/res/edgeCases2.epub',
  EDGE_CASES3: '../../test/res/edgeCases3.epub',
  COMIC: '../../test/res/comic.zip',
  UNZIPPED_COMIC: '../../test/res/comic',
  EXPECTED_COMIC_BOOK: '../../test/res/expectedComicBook.json',
  EXPECTED_COMIC_BOOK_WITH_SIZE: '../../test/res/expectedComicBookWithSize.json',
  COMIC_FIRST: '../../test/res/comic/1.jpg',
  COMIC_BASE64: '../../test/res/comicBase64.txt',
  SORT_TEST: '../../test/res/sort',
  PDF: '../../test/res/tutorial.pdf',
  EXPECTED_PDF_BOOK: '../../test/res/expectedPdfBook.json',
};

export default Paths;
