const Paths = {
  DEFAULT: '../../test/res/default.epub',
  UNZIPPED_DEFAULT: '../../test/res/default',
  ENCRYPTED_DEFAULT: '../../test/res/encryptedDefault.epub',
  EXPECTED_DEFAULT_CONTEXT: '../../test/res/expectedDefaultContext.json',
  EXPECTED_DEFAULT_BOOK: '../../test/res/expectedDefaultBook.json',
  DEFAULT_COVER: '../../test/res/cryptor/Cover.xhtml',
  INVALID_PACKAGE: '../../test/res/invalidPackage.epub',
  NCX_MISSING: '../../test/res/ncxMissing.epub',
  META_INF_MISSING: '../../test/res/metainfMissing.epub',
  OPF_MISSING: '../../test/res/opfMissing.epub',
  EXTRACT_STYLE: '../../test/res/extractStyle.epub',
  UNZIPPED_EXTRACT_STYLE: '../../test/res/extractStyle',
  EXPECTED_EXTRACT_STYLE_CONTEXT: '../../test/res/expectedExtractStyleContext.json',
  EXPECTED_EXTRACT_STYLE_BOOK: '../../test/res/expectedExtractStyleBook.json',
  SPINE_LOADER_ORIGIN: '../../test/res/spineLoader/origin.xhtml',
  SPINE_LOADER_NO_OPTIONS: '../../test/res/spineLoader/noOptions.xhtml',
  SPINE_LOADER_BASE_PATH: '../../test/res/spineLoader/basePath.xhtml',
  SPINE_LOADER_NO_ADAPTER: '../../test/res/spineLoader/noAdapter.json',
  SPINE_LOADER_ADAPTER: '../../test/res/spineLoader/adapter.json',
  SPINE_LOADER_CSS_OPTIONS: '../../test/res/spineLoader/cssOptions.xhtml',
  SPINE_LOADER_CSS_OPTIONS_AND_BASE_PATH: '../../test/res/spineLoader/cssOptionsAndBasePath.xhtml',
  SPINE_LOADER_SERIALIZED_ANCHOR: '../../test/res/spineLoader/serializedAnchor.xhtml',
  COMIC: '../../test/res/comic.zip',
  UNZIPPED_COMIC: '../../test/res/comic',
  EXPECTED_COMIC_BOOK: '../../test/res/expectedComicBook.json',
  COMIC_BASE64: '../../test/res/comicBase64.txt',
};

export default Paths;
