const Paths = {
  DEFAULT: '../../test/res/epub/default.epub',
  UNZIPPED_DEFAULT: '../../test/res/epub/default',
  ENCRYPTED_DEFAULT: '../../test/res/epub/encryptedDefault.epub',
  EXPECTED_DEFAULT_CONTEXT: '../../test/res/epub/expectedDefaultContext.json',
  EXPECTED_DEFAULT_BOOK: '../../test/res/epub/expectedDefaultBook.json',
  DEFAULT_COVER: '../../test/res/epub/cryptor/Cover.xhtml',
  INVALID_PACKAGE1: '../../test/res/epub/invalidPackage1.epub',
  INVALID_PACKAGE2: '../../test/res/epub/invalidPackage2.epub',
  INVALID_PACKAGE3: '../../test/res/epub/invalidPackage3.epub',
  INVALID_PACKAGE4: '../../test/res/epub/invalidPackage4.epub',
  NCX_FILE_MISSING: '../../test/res/epub/ncxFileMissing.epub',
  NCX_ID_NOT_MATCHED: '../../test/res/epub/ncxIdNotMatched.epub',
  NCX_MISSING_IN_OPF: '../../test/res/epub/ncxMissingInOpf.epub',
  META_INF_MISSING: '../../test/res/epub/metainfMissing.epub',
  OPF_MISSING: '../../test/res/epub/opfMissing.epub',
  EXTRACT_STYLE: '../../test/res/epub/extractStyle.epub',
  UNZIPPED_EXTRACT_STYLE: '../../test/res/epub/extractStyle',
  EXPECTED_EXTRACT_STYLE_BOOK: '../../test/res/epub/expectedExtractStyleBook.json',
  SPINE_LOADER_ORIGIN: '../../test/res/epub/spineLoader/origin.xhtml',
  SPINE_LOADER_NO_OPTIONS: '../../test/res/epub/spineLoader/noOptions.xhtml',
  SPINE_LOADER_BASE_PATH: '../../test/res/epub/spineLoader/basePath.xhtml',
  SPINE_LOADER_NO_ADAPTER: '../../test/res/epub/spineLoader/noAdapter.json',
  SPINE_LOADER_ADAPTER: '../../test/res/epub/spineLoader/adapter.json',
  SPINE_LOADER_CSS_OPTIONS: '../../test/res/epub/spineLoader/cssOptions.xhtml',
  SPINE_LOADER_CSS_OPTIONS_AND_BASE_PATH: '../../test/res/epub/spineLoader/cssOptionsAndBasePath.xhtml',
  SPINE_LOADER_SERIALIZED_ANCHOR: '../../test/res/epub/spineLoader/serializedAnchor.xhtml',
  SPINE_LOADER_IGNORE_SCRIPT: '../../test/res/epub/spineLoader/ignoreScript.xhtml',
  EDGE_CASES1: '../../test/res/epub/edgeCases1.epub',
  EDGE_CASES2: '../../test/res/epub/edgeCases2.epub',
  EDGE_CASES3: '../../test/res/epub/edgeCases3.epub',
  COMIC: '../../test/res/comic/comic.zip',
  UNZIPPED_COMIC: '../../test/res/comic/comic',
  EXPECTED_COMIC_BOOK: '../../test/res/comic/expectedComicBook.json',
  EXPECTED_COMIC_BOOK_WITH_SIZE: '../../test/res/comic/expectedComicBookWithSize.json',
  COMIC_FIRST: '../../test/res/comic/comic/1.jpg',
  COMIC_BASE64: '../../test/res/comic/comicBase64.txt',
  SORT_TEST: '../../test/res/comic/sort',
  PDF: '../../test/res/pdf/default.pdf',
  EXPECTED_PDF_RAW_BOOK: '../../test/res/pdf/expectedPdfRawBook.json',
  EXPECTED_PDF_BOOK: '../../test/res/pdf/expectedPdfBook.json',
};

export default Paths;
