export default Book;
declare class Book {
    constructor(rawBook?: {});
    titles: any;
    creators: any;
    subjects: any;
    description: any;
    publisher: any;
    contributors: any;
    dates: any;
    type: any;
    format: any;
    identifiers: any;
    source: any;
    languages: any;
    relation: any;
    coverage: any;
    rights: any;
    version: Version;
    metas: any;
    items: any;
    spines: any;
    ncx: any;
    fonts: any;
    cover: any;
    images: any;
    styles: any;
    guides: any;
    deadItems: any;
    toRaw(): {
        titles: any;
        creators: any;
        subjects: any;
        description: any;
        publisher: any;
        contributors: any;
        dates: any;
        type: any;
        format: any;
        identifiers: any;
        source: any;
        languages: any;
        relation: any;
        coverage: any;
        rights: any;
        version: string;
        metas: any;
        items: any;
        guides: any;
    };
}
import { Version } from "@ridi/parser-core";
