export default {
  PATH_NOT_FOUND: 'Path not found.',
  INVALID_FILE_TYPE: 'Invalid file type.',
  INVALID_INPUT: 'Inavlid input.',
  INVALID_OPTIONS: 'Invalid options.',
  INVALID_OPTION_VALUE: 'Invalid option value.',
  INVALID_PACKAGE: 'Inavlid package.',
  INVALID_XML: 'Invalid XML.',
  META_INF_NOT_FOUND: 'META-INF directroy or container.xml not found.',
  OPF_NOT_FOUND: 'OPF file not found.',
  INVALID_OPF: 'Invalid OPF.',
  NCX_NOT_FOUND: 'NCX file not found.',
  INVALID_NCX: 'Invalid NCX.',
  INVALID_ITEM: 'Invalid item.',
};
