name: Check

on:
  push:
    branches:
      - 'master'

env:
  NODE_VERSION: 14

jobs:
  check:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install node packages
      run: yarn install --frozen-lockfile

    - name: Run lint
      run: yarn lint

    - name: Run test
      run: yarn test

    - name: Submit coverage reports
      uses: codecov/codecov-action@v1
